### PR TITLE
fix: brits imputation test device mismatch

### LINKED ISSUE #10: BRITS imputation test fails on cuda device mismatch
Hi, 
when trying to run imputation tests with commit 6dcc8942459094e3a3fc5e11363f5d712ee8e742 on `dev` branch.

`py3.9_cuda11.3_cudnn8.2.0_0`

```py
$ python -m pytest tests/test_imputation.py

./tests/test_imputation.py::TestBRITS::test_parameters Failed with Error: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
  File ".../unittest/case.py", line 59, in testPartExecutor
    yield
  File ".../unittest/case.py", line 588, in run
    self._callSetUp()
  File ".../unittest/case.py", line 547, in _callSetUp
    self.setUp()
  File ".../PyPOTS/pypots/tests/test_imputation.py", line 98, in setUp
    self.brits.fit(self.train_X, self.val_X)
  File "/PyPOTS/pypots/imputation/brits.py", line 504, in fit
    self._train_model(training_loader, val_loader, val_X_intact, val_X_indicating_mask)
  File "/PyPOTS/pypots/imputation/base.py", line 154, in _train_model
    if np.equal(self.best_loss, float("inf")):
  File .../lib/python3.9/site-packages/torch/_tensor.py", line 732, in __array__
    return self.numpy()
TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.
```

### PR DESCRIPTION
**Pull request by MaciejSkrabski**
attempt to fix #10

### CODE REVIEW

**Comment by MaciejSkrabski** [comment]
By the way, may I suggest using code autoformatter named black? :grin:

**Comment by WenjieDu** [comment]
Hi Maciej, thank you for your patience! I'm sorry for my delayed response. I have run the test cases and the results look fine. I only have one comment for your PR 😉 When you try to fix a bug, please only modify the code that is related to the bug because this can help the reviewer quickly understand what you are working on.

And BTW, what do you mean by 'using code autoformatter named black'? Sounds like a configuration of repository settings on GitHub. 

Last but not least, many thanks for your PR! 😃

**Comment by MaciejSkrabski** [comment]
Hi Wenjie, thank you for reviewing the PR!
Your insight is on point. I really shouldn't have tinkered with the code that does not concern the issue at hand, especially when it is just cosmetics, as it makes analysing code more difficult. I am sorry for being overzealous :grin: 

What I do mean about 'using code autoformatter named black': there's this thing called *black*. It is a python autoformatter, that obides the pep8 code style. It can be used as a standalone program run on *.py files. In that regard it is similar to python linters like pylint. As it can be used in a  standalone manner, I guess it is possible to include it in your GitHub workflows. I think it would either create a new commit on top of what is being pushed to the branch, or ammend the last commit. It can also be used as part of your IDE / text editor while first writing the code - I know it is a no-brainer to setup with VSCode. My colleague, who uses Eclipse, had to tinker with it for a while.

Anyway, *black* makes the indents right, the quotes consistent, the function arguments neatly organised and so much more! It can be parametrised a bit, and the config is just a file that you can keep in the repo, so people automatically use the code style you ask them to, as long as they use black.. Its greatest advantage is that anyone working with the code shares the same style without ever giving it a single thought.

On the other hand, when one party does not use black, and the second party does, the thing that happened to the two of us happens - me, not realising how convoluted my PR will appear to a reviewer, had black configured to run on-file-save, so whenever I hit that CTRL+S shortcut, the python file gets formatted for me. This produces a lot of "file changed" messages on github, all of them just cosmetic.

I swear I am not being payed for advertising black :stuck_out_tongue:

I should not have interfered with good code, which does not concern the issue, just for cosmetics sake. I apologise.

**Comment by WenjieDu** [comment]
Merged. Regarding your recommendation for using [black](https://github.com/psf/black), I will also give it consideration. Thanks for letting me know about this formatting tool. 😊

**Pull request merged**
